# See: https://maps.protomaps.com

pmtiles_source_url := "https://build.protomaps.com/20251229.pmtiles"

# Determine bounding box from address locations
# See: https://docs.protomaps.com/pmtiles/cli#extract

download_map_pmtiles:
    pmtiles extract {{ pmtiles_source_url }} data/colorado.pmtiles \
        --bbox="$()" \
        --minzoom=7 \
        --maxzoom=17

download_addresses:
    uv run download_addresses.py

download_service_lines:
    uv run download_service_lines.py

build_addresses_parquet_table:
    uv run build_addresses_parquet_table.py

convert_addresses_to_geojson:
    uv run convert_addresses_to_geojson.py

convert_addresses_to_pmtiles:
    tippecanoe \
      --force \
      -zg \
      --minimum-zoom=10 \
      --drop-densest-as-needed \
      -o data/addresses.pmtiles \
      data/addresses.geojson

convert_service_lines_to_pmtiles:
    tippecanoe \
      --force \
      -zg \
      --drop-densest-as-needed \
      -o data/service_lines.pmtiles \
      data/service_lines.geojson

get_map_bbox_for_addresses_table:
    duckdb \
      -json \
      -f lib/get_bbox_from_addresses.sql \
      | jq -r '.[0].value'
